#!/usr/bin/env bash
set -eo pipefail; [[ -n "$PLUSHU_TRACE" ]] && set -x

# For instances where a glob has no matches we want an empty list
shopt -s nullglob

if [[ "$EUID" == 0 ]]; then
  if [[ -f /etc/sudoers.d/plushu-reload-nginx ]]; then
    rm /etc/sudoers.d/plushu-reload-nginx
  fi
  if [[ `readlink /etc/nginx/ssl` == "$PLUSHU_ROOT/ssl" ]]; then
    unlink /etc/nginx/ssl
  fi
  if [[ `readlink /etc/nginx` == "$PLUSHU_ROOT/nginx" &&
    -d /etc/nginx.old ]]; then

    unlink /etc/nginx
    mv /etc/nginx.old /etc/nginx
  fi
else
  echo "Not uninstalling anything because this plugin isn't being uninstalled"
  echo "as root. Be sure to clean up your /etc/sudoers configuration and"
  echo "Nginx configuration."
fi
